import type { Metadata } from "next";
import "./globals.css";
import NavBar from "../components/NavBar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden w-[100vw] bg-background bg-opacity-100">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
